<a href="https://colab.research.google.com/github/dprietog/MetNumUN2022II/blob/main/Lab3/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as banana

df=banana.DataFrame({'a':[11,21,31],'b':[21,22,23]})

df.head()

a   b
0  11  21
1  21  22
2  31  23

In [2]:
import pandas as pd
df=pd.DataFrame({'a':[1,2,1],'b':[1,1,1]})
df['a']==1 

0     True
1    False
2     True
Name: a, dtype: bool

In [4]:
import numpy as np

np.array([1,-1])*np.array([1,1])

array([ 1, -1])

In [5]:
np.dot(np.array([1,-1]),np.array([1,1]))

0

In [7]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.dot(A,B)

ValueError: ignored

In [8]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [9]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)

0

In [10]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

In [11]:
3+2*2

7

In [12]:
A='1234567'
A[1::2]

'246'

In [13]:
Name="Michael Jackson" 
Name.find('el')

5

In [14]:
A=((11,12),[21,22])
A[1]

[21, 22]

In [15]:
A=((11,12),[21,22])
A[0][1]

12

In [18]:
V={'A','B'}
V.add('C')
print(V)
V.add('C')

{'B', 'C', 'A'}


In [19]:
x="Go"

if(x!="Go"):

  print('Stop')

else:

  print('Go ')

print('Mike')




Go 
Mike


In [20]:
x="Go"

if(x=="Go"):

  print('Go ')

else:

  print('Stop')

print('Mike')




Go 
Mike


In [23]:
for i in range(3):
  print(i+1)

1
2
3


In [24]:
A=['1','2','3']

for a in A:

  print(2*a)

11
22
33


In [26]:
def Add(x,y):

  z=y+x

  return(y)

Add('1', '1')

'1'

In [28]:
class Points(object):

  def __init__(self,x,y):

    self.x=x

    self.y=y

  def print_point(self):

    print('x=',self.x,'y=',self.y)
p2 = Points(1, 2)
p2.x = 2
p2.print_point()

x= 2 y= 2
